defmodule Book.Repo.Migrations.AddAuthors do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:authors, primary_key: false) do
      add :author_id, :bigserial, null: false, primary_key: true
      add :first_name, :text, null: false
      add :last_name, :text, null: false
      add :biography, :text
      add :nationality, :text
      add :birth_date, :date
      add :death_date, :date

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:authors)
  end
end
