defmodule Book.Repo.Migrations.Borowing do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:borrowings, primary_key: false) do
      add :borrowing_id, :bigserial, null: false, primary_key: true

      add :member_id,
          references(:users,
            column: :id,
            name: "borrowings_member_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :book_id,
          references(:books,
            column: :book_id,
            name: "borrowings_book_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          null: false

      add :issue_date, :date, null: false
      add :due_date, :date, null: false
      add :return_date, :date
      add :status, :text
      add :fine_amount, :decimal

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:borrowings, "borrowings_member_id_fkey")

    drop constraint(:borrowings, "borrowings_book_id_fkey")

    drop table(:borrowings)
  end
end
