defmodule Book.Repo.Migrations.AuthorBooksFix do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:book_authors, primary_key: false) do
      add :book_id,
          references(:books,
            column: :book_id,
            name: "book_authors_book_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :author_id,
          references(:authors,
            column: :author_id,
            name: "book_authors_author_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:book_authors, "book_authors_book_id_fkey")

    drop constraint(:book_authors, "book_authors_author_id_fkey")

    drop table(:book_authors)
  end
end
