defmodule Book.Repo.Migrations.Reservation do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:reservations) do
      modify :member_id, :text
    end
  end

  def down do
    alter table(:reservations) do
      modify :member_id, :bigint
    end
  end
end
