defmodule Book.Repo.Migrations.AddBooks do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:books, primary_key: false) do
      add :book_id, :bigserial, null: false, primary_key: true
      add :isbn, :text, null: false
      add :title, :text, null: false
      add :author, :text, null: false
      add :publisher_id, :bigint
      add :publication_date, :date
      add :genre, :text
      add :language, :text
      add :total_copies, :bigint
      add :available_copies, :bigint
      add :price, :decimal
      add :status, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop table(:books)
  end
end
