defmodule Book.Repo.Migrations.BookCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:book_categories, primary_key: false) do
      add :category_id,
          references(:categories,
            column: :category_id,
            name: "book_categories_category_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :book_id,
          references(:books,
            column: :book_id,
            name: "book_categories_book_id_fkey",
            type: :bigint,
            prefix: "public"
          ),
          primary_key: true,
          null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    drop constraint(:book_categories, "book_categories_category_id_fkey")

    drop constraint(:book_categories, "book_categories_book_id_fkey")

    drop table(:book_categories)
  end
end
